### ISSUE TITLE
.isBoolean function having a AND operator instead of OR. 

### ISSUE THREAD

**Issue by iamsurajdc** [andrewjmead/node-course-2-todo-api#1]
@andrewjmead 
So, the program code : 

`if(body.completed && _.isBoolean(body.completed)) `

is generating false value due to AND's behavior.

**Comment by andrewjmead** [comment]
What the _completed_ value you're using?

**Comment by iamsurajdc** [comment]
> What the _completed_ value you're using?

I am using true, and in mongoose record it is false.

**Comment by andrewjmead** [comment]
I tested things out with the lecture code and wasn't able to recreate this. `true` would indeed cause both of those conditions to pass. It is true, and it is a boolean.

**Comment by iamsurajdc** [comment]
Thank You @andrewjmead for your highly appreciable help during the issue. It's working now.
